class AppStrings {
  AppStrings._();
  static const String taskViewHeader = 'hmm its seems you want do something..';
  static const String taskViewTitle = 'title';
  static const String taskViewDescription = 'description';
  static const String taskViewAddOne = 'Add New ';
  static const String taskViewUpdate = 'Update';
  static const String taskViewAddTwo = 'Task';
  static const String taskViewTime = 'Time';
  static const String taskViewDate = 'Date';
  static const String taskViewSelectTime = 'Select Time';
  static const String taskViewSelectDate = 'Select Date';
  static const String taskViewAddTask = 'Add Task';
  static const String taskViewDeleteTask = 'Delete Task';
  static const String taskViewInputOne = 'what are you planing ?';
  static const String taskViewInputTwo = 'add note to remember';
  static const String homeViewMyTasks = 'My Tasks';
  static const String homeViewDelete = 'This Task Was deleted';
  static const String homeViewEmpty = 'You Done All Tasks';
  static const String homeViewEmptyJson = 'assets/empty_box.json';
  static const String drawerProfile = 'Profile';
  static const String drawerHome = 'Home';
  static const String drawerSetting = 'Setting';
  static const String drawerShare = 'Share';
  static const String dialogEmptyTask = 'dont have any task to delete';
  static const String dialogOops = 'Oops !';
  static const String dialogOk = 'Ok';
  static const String dialogDeteleTask = 'We Gonna Delete All Task';
  static const String dialogAreSure = 'Are You Sure ?';
  static const String dialogDelete = 'Yes Delete';
  static const String dialogCancle = 'Cancl';
  static const String toastPleaseEdit = 'please edit task then try again';
  static const String toastPleaseInsert = 'please insert all fields first';
  static const String timeFormatter = 'hh : mm : ss a';
  static const String dateFormatter = 'yyyy-MM-dd';
}
